"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var BalancingSymbols_1 = require("./BalancingSymbols");
var Postfix_1 = require("./Postfix");
var ScientificCalulator_1 = require("./ScientificCalulator");
var sym = new BalancingSymbols_1.BalancingSymbols("[[]]");
sym.toString();
sym.check();
var pos = new Postfix_1.Postfix();
pos.add(6, 5, 2, 3, "+", 8, "*", "+", 3, "+", "*");
pos.evaluate();
pos.toString();
var cal = new ScientificCalulator_1.ScientificCalulator("(20+5)*2/2*2-25*2-1");
cal.value();
